[package]
name = "armor_trims"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quartz_nbt = {version = "0.2.6", features = ["serde"]}
anyhow = "1"
serde = {version = "1", features = ["derive"]}